/*
|--------------------------------------------------------------------------
| Routes
|--------------------------------------------------------------------------
|
| This file is dedicated for defining HTTP routes. A single file is enough
| for majority of projects, however you can define routes in different
| files and just make sure to import them inside this file. For example
|
| Define routes in following two files
| ├── start/routes/cart.ts
| ├── start/routes/customer.ts
|
| and then import them inside `start/routes.ts` as follows
|
| import './routes/cart'
| import './routes/customer'
|
*/

import Route from '@ioc:Adonis/Core/Route'

Route.get('/', 'AppController.index')
Route.get('/test', 'TestController.test')

Route.get('/cron', 'AppController.cron')
Route.get('/hourly', 'AppController.hourly')
Route.get('/daily', 'AppController.daily')

Route.get('/socket.io/', () => '')
Route.post('/socket.io/', () => '')
Route.get('/favicon.ico', () => '')
Route.get('/search-address', 'AppController.searchAddress')
Route.get('/detail-address', 'AppController.detailAddress')

Route.get('/robots.txt', ({ response }) => {
  response.header('Content-type', 'text/plain')
  return 'User-agent: *\nDisallow: /'
})

Route.get('/adonis-ws', () => {
  return 'adonis-ws'
})
/**
Route.get('/loaderio-a0da777c23dadd71d60bd04d8816419d.txt', ({ response }) => {
  response.header('Content-type', 'text/plain')
  return 'loaderio-a0da777c23dadd71d60bd04d8816419d'
})
**/

// Intercom
Route.group(() => {
  // Language conf
  Route.post('/language-conf', 'IntercomController.configureLanguage')

  // Orders bot
  Route.post('/orders-init', 'IntercomController.initOrder')
  Route.post('/orders-submit', 'IntercomController.submitOrder')

  // Account bot
  Route.post('/account-init', 'IntercomController.initAccount')
  Route.post('/account-submit', 'IntercomController.submitAccount')
})
  .prefix('intercom')
  .middleware('intercom')

// Digital

Route.group(() => {
  Route.group(() => {
    Route.post('/create', 'DigitalController.createDigitalProject')
    Route.put('/:id/tracks', 'DigitalController.saveTrack')
    Route.post('/:id/tracks', 'DigitalController.saveTrack')
    Route.post('/:id/tracks-new', 'DigitalController.saveTrackNew')
    Route.delete('/:project_id/tracks/:id', 'DigitalController.deleteTrack')
    Route.get('/:id/artwork', 'DigitalController.getArtwork')
    Route.get('/', 'DigitalController.getAll')
    Route.post('/', 'DigitalController.createAdmin')
    Route.get('/export', 'DigitalController.export')
    Route.post('/duplicate/:id', 'DigitalController.duplicate')
    Route.get(':id', 'DigitalController.getDigitalSingle')
    Route.get(':id/download', 'DigitalController.downloadFile')
    Route.get(':id/files', 'DigitalController.getFiles')
    Route.post(':did/files', 'DigitalController.addFile')
    Route.post(':did/files/:id', 'DigitalController.updateFile')
    Route.delete(':did/files/:id', 'DigitalController.deleteFile')
    Route.put(':id', 'DigitalController.update')
    Route.delete(':id', 'DigitalController.delete')
    Route.post('/new', 'DigitalController.createOne')
    Route.get('/new/:id', 'DigitalController.getOne')
  }).prefix('digital')
}).middleware(['auth'])

Route.get('/digital/:id/songs', 'DigitalController.getSongs')

Route.group(() => {
  Route.get('/projects', 'DigitalController.getDigitalProjectsByUser')
})
  .prefix('user/digital')
  .middleware(['auth'])

Route.group(() => {
  Route.get('/emails/:id', 'AppController.previewEmail')
})
  .prefix('app')
  .middleware('app')

Route.group(() => {
  Route.get('/styles', 'AppController.getStyles')
  Route.get('/genres', 'AppController.getGenres')
  Route.get('/press', 'AppController.getPress')
  Route.post('/contact', 'AppController.contact')
  Route.get('/boxes', 'BoxController.getLastBoxes')
  Route.get('/boxes/prices', 'BoxController.getBoxesPrices')
  Route.post('/boxes/sponsor', 'BoxController.checkSponsor').middleware(['auth:optional'])
  Route.post('/quote', 'AppController.sendQuote')
  Route.post('/quote/calculate', 'AppController.calculateQuote')

  Route.get('/banners', 'AppController.getBanners')
  Route.get('/home', 'AppController.getHome')

  Route.get('/songs', 'SongsController.all')
  Route.post('/songs/stats', 'SongsController.addPlay')

  Route.post('/payments', 'AppController.payPayment')
  Route.get('/payments/:id', 'AppController.getPayment')
  Route.put('/payments/:id/address', 'AppController.editPaymentAddress')

  Route.post('/comments', 'CommentsController.save')

  Route.get('/blog', 'BlogController.all')
  Route.get('/blog/:id', 'BlogController.find')

  Route.get('/shops/:id', 'ShopController.find')

  Route.post('projects/check-code', 'ProjectsController.checkCode')
  Route.post('/projects/download', 'ProjectsController.download')
  Route.get('/projects', 'ProjectsController.getProjects')
  Route.get('/projects/all', 'ProjectsController.getAll')
  Route.get('/projects/recommandations', 'ProjectsController.recommandations')
  Route.get('/projects/recommandations-for-user', 'ProjectsController.recommandationsForUser')
  Route.get('/projects/soundcloud', 'ProjectsController.getSoundcloud')
  Route.get('/projects/dashboard', 'ProjectsController.getDashboard')
  Route.get('/projects/:id', 'ProjectsController.find')
  Route.get('/projects/:id/more', 'ProjectsController.getMore')
  Route.get('/projects/:id/group-shipment', 'ProjectsController.getGroupShipment')
  Route.get('/projects/:id/songs', 'ProjectsController.getSongs')
  Route.get('/projects/:id/edit', 'ProjectsController.findEdit')
  Route.get('/projects/:id/stats', 'ProjectsController.getStats')
  Route.get('/projects/:id/orders', 'ProjectsController.getOrders')
  Route.get('/projects/:id/statement', 'ProjectsController.downloadStatement')
  Route.post('/projects', 'ProjectsController.saveProject')
  Route.post('/projects/:id/artwork', 'ProjectsController.updateArtwork')
  Route.post('/projects/:id/tracks', 'ProjectsController.saveTrack')
  Route.post('/projects/:id/tracks-new', 'ProjectsController.saveTrackNew')
  Route.put('/projects/:id/tracks', 'ProjectsController.saveTracks')
  Route.post('/projects/:id/tracks/:tid/encode', 'ProjectsController.encodeTrack')
  Route.delete('/projects/:project_id/tracks/:id', 'ProjectsController.deleteTrack')

  Route.get('/users', 'UsersController.all')
  Route.get('/users/:id', 'UsersController.find')

  Route.get('/bids/:id', 'BidController.find')
  Route.post('/bids/:id/pay', 'BidController.pay')
  Route.post('/bids/:id/pay-confirm', 'BidController.payConfirm')
  Route.post('/bids/:id/address', 'BidController.editAddress')
  Route.post('/bids/:id/valid', 'BidController.valid')
  Route.post('/bids/:id/cancel', 'BidController.cancel')
}).middleware('auth:optional')

Route.get('/auth/check', 'AuthController.check').middleware(['auth'])
Route.post('/auth/login', 'AuthController.login')
Route.post('/auth/facebook', 'AuthController.facebook')
Route.post('/auth/google', 'AuthController.google')
Route.get('/auth/soundcloud', 'AuthController.soundcloud')
Route.post('/auth/soundcloud', 'AuthController.soundcloud')
Route.post('/auth/signup', 'AuthController.signup')
Route.post('/auth/check-email', 'AuthController.checkEmail')
Route.post('/auth/confirm', 'AuthController.confirm')
Route.post('/auth/forgot-password', 'AuthController.forgotPassword')
Route.post('/auth/reset-password', 'AuthController.resetPassword')
Route.post('/auth/unsubscribe-newsletter', 'AuthController.unsubscribeNewsletter')

Route.post('/cart/calculate', 'CartController.calculate').middleware(['auth:optional'])
Route.post('/cart/pay', 'CartController.pay').middleware(['auth:optional'])
Route.post('/cart/confirm', 'CartController.confirm').middleware(['auth:optional'])
Route.post('/cart/related', 'CartController.related').middleware(['auth:optional'])
Route.post('/cart/feedback', 'CartController.saveFeedback').middleware(['auth:optional'])
Route.post('/vod/:id/calculate', 'ProjectsController.calculateVod').middleware(['auth:optional'])

Route.get('/contests/:id', 'ContestController.find')
Route.put('/boxes/code', 'CartController.checkBoxCode')

Route.post('/newsletter', 'AppController.subscribeNewsletterWithoutAccount')
Route.post('/pass-culture', 'AppController.subscribeToPassCulture')

Route.get('/catalog', 'AdminController.exportCatalog')
Route.get('/projects-selection', 'ProjectsController.getProjectSelection')
Route.get('/stats/top-projects', 'ProjectsController.getTopProjects')

Route.get('/featured/all', 'UserController.getAllFeatured')

Route.get('/linktree', 'AdminController.getLinktree')
Route.get('/linktree/:id', 'AdminController.getOneLinktree')

Route.group(() => {
  Route.get('/cart', 'CartController.getCart')
  Route.post('/cart', 'CartController.saveCart')
  Route.delete('/cart', 'CartController.clearCart')
  Route.post('/boxes/code', 'CartController.confirmBoxCode')

  Route.post('/projects/:id/like', 'ProjectsController.like')
  Route.post('/projects/call-me', 'ProjectsController.callMe')

  Route.post('/contests', 'ContestController.join')

  Route.get('/productions', 'ProductionController.all')
  Route.post('/productions', 'ProductionController.create')
  Route.post('/productions/extract', 'ProductionController.extract')
  Route.get('/productions/:id', 'ProductionController.find')
  Route.put('/productions/:id', 'ProductionController.save')
  Route.delete('/productions/:id', 'ProductionController.remove')
  Route.post('/productions/:id/comment', 'ProductionController.saveComment')
  Route.get('/productions/:id/actions', 'ProductionController.getAction')
  Route.post('/productions/:id/actions', 'ProductionController.saveAction')
  Route.get('/productions/:id/download', 'ProductionController.downloadFile')
  Route.get('/productions/:id/zip', 'ProductionController.zipFiles')
  Route.put('/productions/:id/files', 'ProductionController.saveFile')
  Route.delete('/productions/:id/files', 'ProductionController.deleteFile')
  Route.get('/productions/:id/dispatchs', 'ProductionController.getDispatchs')
  Route.post('/productions/:id/dispatchs', 'ProductionController.saveDispatch')
  Route.put('/productions/:id/dispatchs', 'ProductionController.saveDispatchUser')
  Route.get('/productions/:id/dispatchs/:did/file', 'ProductionController.fileDispatch')
  Route.post('/productions/:id/invoice-co', 'ProductionController.saveInvoiceCo')
  Route.get('/productions/:id/packing-list', 'ProductionController.packingList')
  Route.post('/productions/:id/lines', 'ProductionController.saveLines')
  Route.delete('/productions/:id/dispatchs/:did', 'ProductionController.removeDispatch')
  Route.get(
    '/productions/:id/notifications/:tid',
    'ProductionController.checkIfActionHasNotifications'
  )

  Route.get('/shops', 'ShopController.getShops')
  Route.get('/shop', 'ShopController.getShop')
  Route.post('/shop', 'ShopController.updateShop')
  Route.post('/shop/code', 'ShopController.checkCode')
  Route.post('/shop/project', 'ShopController.addProject')
  Route.delete('/shop/project', 'ShopController.removeProject')
  Route.post('/shop/project/position', 'ShopController.changeProjectPosition')
  Route.post('/shop/project/featured', 'ShopController.setFeatured')
  Route.delete('/shop/image', 'ShopController.removeShopImage')
}).middleware('auth')

Route.get('/productions/:id/order-form', 'ProductionController.orderForm')

Route.group(() => {
  Route.post('/profile', 'UserController.updateProfile')
  Route.post('/currency', 'UserController.updateCurrency')
  Route.post('/lang', 'UserController.updateLang')
  Route.post('/password', 'UserController.updatePassword')
  Route.post('/delivery', 'UserController.updateDelivery')
  Route.post('/notifications', 'UserController.updateNotifications')
  Route.post('/notifications/view', 'UserController.setNotificationsView')
  Route.post('/picture', 'UserController.updatePicture')
  Route.get('/messages', 'UserController.getMessages')
  Route.post('/messages', 'UserController.sendMessage')
  Route.get('/messages/:from', 'UserController.getMessagesByUser')
  Route.get('/projects', 'UserController.getProjects')
  Route.get('/projects/:id/orders', 'UserController.getProjectOrders')
  Route.get('/projects/:id/extract-orders', 'UserController.extractProjectOrders')
  Route.get('/orders', 'UserController.getOrders')
  Route.get('/orders/:id/tracking', 'UserController.getTrackingDelivery')
  Route.get('/orders/:id/shop', 'UserController.getOrderShop')
  Route.put('/orders/:id/customer', 'UserController.updateOrderCustomer')
  Route.get('/orders/:id/download', 'UserController.downloadOrderTracks')
  Route.delete('/orders/:id', 'UserController.cancelOrder')
  Route.get('/boxes/:id', 'UserController.getBox')
  Route.get('/boxes', 'UserController.getBoxes')
  Route.put('/boxes', 'UserController.changeBox')
  Route.post('/boxes/vinyl', 'UserController.selectBoxVinyl')
  Route.post('/boxes/invoice', 'UserController.boxInvoice')
  Route.post('/boxes/payment', 'UserController.changeBoxPayment')
  Route.post('/boxes/address', 'UserController.changeBoxAddress')
  Route.get('/card', 'UserController.getCard')
  Route.delete('/boxes/:id', 'UserController.cancelBox')
  Route.get('/boxes/:bid/reviews', 'UserController.getBoxReviews')
  Route.get('/boxes/:bid/reviews/:uid', 'UserController.checkUserHasReviewedBox')
  Route.get('/digs', 'UserController.getDigs')
  Route.get('/cards', 'UserController.getCards')
  Route.post('/cards', 'UserController.saveCards')
  Route.post('/event', 'UserController.event')
  Route.get('/sponsor', 'UserController.getSponsor')
  Route.get('/reviews', 'UserController.getReviews')
  Route.post('/reviews', 'UserController.postReview')
  Route.post('/reviews/stat', 'UserController.postReviewStat')
  Route.get('/projects/:pid/reviews', 'UserController.getProjectReviews')

  // Pass
  Route.get('/pass', 'UserController.getPass')
  Route.get('/pass/quest-progress', 'UserController.getPassQuestProgress')
  Route.get('/pass/badge-progress', 'UserController.getPassBadgeProgress')
  Route.post('/pass/gift/:id/claim', 'UserController.claimGift')

  Route.post('/wishes', 'UserController.saveWish')
  Route.post('/follows/:id', 'UserController.follow')
  Route.get('/wishes/project/:id', 'ProjectsController.getWishes')
})
  .prefix('user')
  .middleware(['auth'])

Route.group(() => {
  Route.get('/stats', 'AdminController.getStats')
  Route.get('/stats2', 'AdminController.getStats2')
  Route.post('/linktree', 'AdminController.saveLinktree')
  Route.post('/linktree/:id', 'AdminController.saveLinktree')
  Route.post('/linktree/:id/links', 'AdminController.saveLinktreeLink')
  Route.delete('/linktree/:id', 'AdminController.deleteLinktree')
  Route.get('/business', 'AdminController.getBusiness')
  Route.get('/resp-prod', 'AdminController.getRespProd')
  Route.get('/stripe-balance', 'AdminController.getStripeBalance')
  Route.post('/customers', 'AdminController.saveCustomer')
  Route.get('/alerts', 'AdminController.getAlerts')
  Route.get('/alerts/:id', 'AdminController.getAlert')
  Route.post('/alerts/:id', 'AdminController.saveAlert')
  Route.post('/customers', 'AdminController.saveCustomer')
  Route.get('/shops', 'ShopController.all')
  Route.get('/projects', 'AdminController.getProjects')
  Route.get('/projects/export', 'AdminController.exportProjects')
  Route.get('/projects/export-raw', 'AdminController.exportRawProjects')
  Route.get('/projects/balance', 'AdminController.getBalances')
  Route.get('/projects/boxes-export', 'AdminController.exportProjectsBox')
  Route.get('/projects/turnover', 'AdminController.getProjectsTurnover')
  Route.get('/projects/:id', 'AdminController.getProject')
  Route.post('/projects/:id', 'AdminController.saveProject')
  Route.get('/projects/:id/balance', 'AdminController.getBalance')
  Route.post('/projects/:id/send-notif', 'AdminController.sendProjectNotif')
  Route.get('/projects/:id/code-download', 'App/Project.codeDownload')
  Route.post('/projects/:id/tracks', 'AdminController.uploadTracks')
  Route.post('/projects/:id/transfer', 'AdminController.transferStripe')
  Route.post('/projects/:id/reverse', 'AdminController.reverseStripe')
  Route.post('/projects/:id/payout', 'AdminController.payoutStripe')
  Route.get('/projects/:id/statements', 'AdminController.getStatements')
  Route.post('/projects/:id/statements', 'AdminController.saveStatement')
  Route.post('/projects/:id/images', 'AdminController.saveProjectImage')
  Route.post('/projects/:id/products', 'ProductController.saveProject')
  Route.delete('/projects/:id/products', 'ProductController.removeProject')
  Route.post('/projects/:id/stock', 'AdminController.setStock')
  Route.put('/projects/:id/images/:iid', 'AdminController.updateProjectImage')
  Route.delete('/projects/:id/images/:iid', 'AdminController.deleteProjectImage')
  Route.get('/projects/:id/statements/download', 'AdminController.downloadStatement')
  Route.delete('/projects/:id/statements/:sid', 'AdminController.deleteStatement')
  Route.delete('/projects/:id', 'AdminController.deleteProject')
  Route.get('/projects/:id/stats', 'AdminController.getProjectStats')
  Route.get('/projects/:id/reviews', 'AdminController.getProjectReviews')
  Route.get('/projects/:id/orders/extract', 'AdminController.extractOrders')
  Route.get('/projects/:id/check-sync', 'AdminController.checkSync')
  Route.post('/projects/:id/orders/sync-project', 'AdminController.syncProject')
  Route.get('/projects/:id/calcul-stock', 'AdminController.calculStock')
  Route.get('/projects/:id/songs', 'AdminController.downloadProject')
  Route.get('/projects/:id/promo-kit', 'AdminController.downloadPromoKit')
  Route.post('/projects/:id/duplicate', 'AdminController.duplicateProject')
  Route.get('/projects/:id/export-mails/:lang', 'AdminController.exportEmails')
  Route.post('/projects/:id/generate-download', 'AdminController.generateDownloads')
  Route.get('/projects/:id/download-codes', 'AdminController.downloadCodes')
  Route.post('/projects/:id/balance', 'AdminController.getBalanceProject')
  Route.delete('/projects/:id/picture', 'AdminController.removePicture')
  Route.post('/projects/:id/costs', 'ProductionController.storeCosts')
  Route.delete('/projects/:id/costs', 'ProductionController.deleteCost')
  Route.get('/projects/:id/productions', 'ProductionController.getProjectProductions')
  Route.get('/projects/:id/costs/:cid/download', 'ProductionController.downloadInvoiceCost')
  Route.put('/projects/:id/reviews/:rid', 'AdminController.updateReview')
  Route.delete('/projects/:id/reviews/:rid', 'AdminController.deleteReview')
  Route.get('/projects/:id/dispatchs', 'AdminController.getDispatchs')
  Route.get('/projects/facebook', 'AdminController.exportFacebookProjects')
  Route.delete('/projects/:id/remove-image', 'AdminController.removeImage')
  Route.post('/projects/:id/redo-check-address', 'AdminController.redoCheckAddress')
  Route.get('/projects/:pid/delay-nl', 'AdminController.getDelayNewsletters')
  Route.put('/projects/:pid/delay-nl', 'AdminController.putDelayNewsletter')
  Route.get('/stats/direct-pressing', 'AdminController.getStatsDirectPressing')
  Route.delete('/projects/:pid/delay-nl/:dnlid', 'AdminController.deleteDelayNewsletter')
  Route.post('/statements', 'AdminController.uploadStatement')
  Route.get('/statements/stats', 'AdminController.getStatementStats')
  Route.get('/statements/:id/download', 'AdminController.downloadHistoryStatement')
  Route.get('/statements/countries', 'AdminController.getSalesByCountry')
  Route.get('/statements/licences', 'AdminController.getSalesLicences')
  Route.post('/stocks', 'AdminController.uploadStocks')
  Route.post('/items', 'AdminController.saveProjectItem')
  Route.delete('/items/:id', 'AdminController.removeProjectItem')
  Route.post('/projects/:id/refund', 'AdminController.refundProject')
  Route.get('/wishlists', 'AdminController.getWishlists')
  Route.post('/stripe/:id', 'AdminController.updateAccount')
  Route.delete('/stripe/:id', 'AdminController.deleteAccount')
  Route.get('/orders/errors', 'AdminController.countOrdersError')
  Route.get('/orders', 'AdminController.getOrders')
  Route.get('/orders/:id', 'AdminController.getOrder')
  Route.get('/orders-shop/:id', 'AdminController.getOrderShop')
  Route.get('/ordershops/:id/invoice', 'AdminController.getOrderShopInvoice')
  Route.post('/orders', 'AdminController.saveOrder')
  Route.get('/order-export', 'AdminController.extractOrders')
  Route.get('/order-export/refunds', 'AdminController.exportOrdersRefunds')
  Route.get('/order-export/commercial', 'AdminController.exportOrdersCommercial')
  Route.get('/sales-export', 'AdminController.exportSales')
  Route.get('/ca-export', 'AdminController.exportCaByProjectId')
  Route.get('/reviews-export', 'AdminController.exportReviews')
  Route.post('/orders/import', 'AdminController.importOrders')
  Route.post('/orders/:id', 'AdminController.saveOrderShop')
  Route.post('/orders/:id/sync', 'AdminController.syncOrder')
  Route.post('/orders/:id/items', 'AdminController.saveOrderItem')
  Route.get('/orders/:id/download', 'AdminController.downloadOrder')
  Route.post('/orders/:id/refund', 'AdminController.refundOrder')
  Route.get('/orders/:osid/check-rest/:pid', 'AdminController.checkProjectRest')
  Route.post('/orders/:id/credit-note', 'AdminController.orderCreditNote')
  // Route.get('/reviews/:id', 'AdminController.getReview')
  Route.post('/orders/:id/shipping-payment', 'AdminController.shippingPayment')
  Route.post('/orders/:id/pickup-change', 'AdminController.pickupMustChange')
  Route.delete('/orders/:id/refund', 'AdminController.refundOrderShop')
  Route.delete('/orders/:id', 'AdminController.cancelOrderShop')
  Route.get('/orders/:id/customer', 'AdminController.getCustomerByOrderShopId')
  Route.get('/feedbacks', 'AdminController.getFeedbacks')
  Route.get('/feedbacks/pending', 'AdminController.getPendingFeedbacks')
  Route.post('/feedbacks/:id/contact', 'AdminController.toggleFeedbackContactStatus')
  Route.get('/feedbacks/stats', 'AdminController.getMonthlyFeedbackStats')
  Route.get('/feedbacks/export', 'AdminController.exportFeedbacks')
  Route.get('/reviews/projects', 'AdminController.getProjectsReviews')
  Route.get('/reviews/boxes', 'AdminController.getBoxesReviews')
  Route.get('/reviews/pending', 'AdminController.getPendingReviews')
  Route.get('/reviews/stats', 'AdminController.getReviewsStats')
  Route.get('/boxes', 'BoxController.getBoxes')
  Route.get('/boxes/export', 'BoxController.exportBoxes')
  Route.get('/boxes/dispatchs', 'BoxController.statsDispatchs')
  Route.get('/boxes/dispatchs/export', 'BoxController.exportDispatchs')
  Route.get('/boxes/months', 'BoxController.getBoxMonths')
  Route.post('/boxes/months', 'BoxController.saveBoxMonth')
  Route.delete('/boxes/months', 'BoxController.removeBoxMonth')
  Route.get('/boxes/stats', 'BoxController.getBoxesStats')
  Route.get('/boxes/codes', 'BoxController.getBoxCodes')
  Route.post('/boxes/codes', 'BoxController.saveBoxCode')
  Route.get('/boxes/:id', 'BoxController.getBox')
  Route.get('/boxes/:id/card', 'BoxController.getBoxCard')
  Route.post('/boxes/dispatch', 'BoxController.saveDispatch')
  Route.get('/boxes/dispatch/:id/invoice', 'BoxController.invoiceDispatch')
  Route.post('/boxes/:id', 'BoxController.saveBox')
  Route.get('/boxes/:id/dispatch-refresh', 'BoxController.refreshBoxDispatch')
  Route.post('/boxes/check', 'BoxController.checkPayments')
  Route.post('/boxes/:id/payments/:obid', 'BoxController.refundBoxPayment')
  Route.delete('/boxes/dispatch/:id', 'BoxController.removeDispatch')
  Route.get('/barcodes/:code', 'ProjectsController.getBarcode')
  Route.get('/users', 'AdminController.getUsers')
  Route.get('/users/extract', 'AdminController.extractUsers')
  Route.get('/users/audiences', 'AdminController.getAudiences')
  Route.get('/users/unsubscribed', 'AdminController.getUnsubscribed')
  Route.post('/users/unsub', 'AdminController.newsletterUnsub')
  Route.get('/users/:id', 'AdminController.getUser')
  Route.get('/users/:id/emails', 'AdminController.getUserEmails')
  Route.delete('/users/:id', 'AdminController.deleteUser')
  Route.post('/users/:id', 'AdminController.saveUser')
  Route.post('/users/:id/digs', 'AdminController.addDig')
  Route.get('/users/:id/statements', 'AdminController.getUserStatements')
  Route.get('/users/:id/statements2', 'AdminController.getUserStatements2')
  Route.get('/users/:id/stock', 'AdminController.getUserStock')
  Route.get('/users/:id/products', 'AdminController.getUserProducts')
  Route.get('/users/:id/balance', 'AdminController.getUserBalance')
  Route.get('/newsletters', 'AdminController.getNewsletters')
  Route.post('/newsletters/template', 'AdminController.getNewsletterTemplate')
  Route.get('/newsletters/:id', 'AdminController.getNewsletter')
  Route.post('/newsletters/:id', 'AdminController.saveNewsletter')
  Route.post('/newsletters/:id/clear-list', 'AdminController.clearNewsletterList')
  Route.post('/newsletters/:id/send', 'AdminController.sendNewsletter')
  Route.post('/newsletters/:id/send-test', 'AdminController.sendNewsletterTest')
  Route.delete('/newsletters/:id', 'AdminController.deleteNewsletter')
  Route.get('/articles', 'BlogController.getArticles')
  Route.get('/articles/:id', 'BlogController.getArticle')
  Route.post('/articles/:id', 'BlogController.saveArticle')
  Route.delete('/articles/:id', 'BlogController.deleteArticle')
  Route.get('/ban', 'AdminController.getBanners')
  Route.post('/ban', 'AdminController.saveBanner')
  Route.get('/ban/:id', 'AdminController.getBanner')
  Route.delete('/ban/:id', 'AdminController.deleteBanner')
  Route.get('/categories', 'AdminController.getCategories')
  Route.get('/categories/:id', 'AdminController.getCategory')
  Route.post('/categories/:id', 'AdminController.saveCategory')
  Route.post('/categories/:id/duplicate', 'AdminController.duplicateCategory')
  Route.post('/categories/:id/populate', 'AdminController.populateProjectsCategory')
  Route.delete('/categories/:id/deleteAll', 'AdminController.deleteAllProjectsCategory')
  Route.delete('/categories/:id', 'AdminController.deleteCategory')
  Route.post('/products/create-items', 'ProductController.createItems')
  Route.get('/products', 'ProductController.getProducts')
  Route.get('/products/:id', 'ProductController.getProduct')
  Route.post('/products/:id', 'ProductController.saveProduct')
  Route.delete('/products/:id', 'ProductController.removeProduct')
  Route.post('/products/:id/stocks', 'ProductController.saveStocks')
  Route.post('/products/:id/stocks/calcul', 'ProductController.setStockProduct')
  Route.post('/products/:id/sub-product', 'ProductController.saveSubProduct')
  Route.delete('/products/:id/sub-product', 'ProductController.removeSubProduct')
  Route.post('/products', 'AdminController.updateProduct')
  Route.get('/surveys', 'AdminController.getSurveys')
  Route.get('/surveys/:id', 'AdminController.getSurvey')
  Route.post('/surveys/:id', 'AdminController.saveSurvey')
  Route.get('/listing', 'AdminController.getListings')
  Route.get('/listing/:id', 'AdminController.getListing')
  Route.post('/listing/:id', 'AdminController.saveListing')
  Route.delete('/listing/:id', 'AdminController.deleteListing')
  Route.get('/propects', 'AdminController.getPropects')
  Route.post('/propects', 'AdminController.newProspect')
  Route.put('/propects', 'AdminController.updateProspect')
  Route.delete('/propects/:id', 'AdminController.deleteProspect')
  Route.get('/labels', 'AdminController.getLabels')
  Route.get('/labels/:id', 'AdminController.getLabel')
  Route.post('/labels', 'AdminController.saveLabel')
  Route.delete('/labels/:id', 'AdminController.deleteLabel')
  Route.post('/labels/:id/copy', 'AdminController.copyLabel')
  Route.get('/parse-label', 'AdminController.parseLabels')
  Route.get('/marketplaces', 'AdminController.getMarketplaces')
  Route.get('/marketplaces/:id', 'AdminController.getMarketplace')
  Route.post('/marketplaces/:id', 'AdminController.saveMarketplace')
  Route.post('/styles', 'AdminController.saveStyles')
  Route.get('/sponsors', 'AdminController.getSponsors')
  Route.post('/sponsors', 'AdminController.saveSponsor')
  Route.get('/promo-codes', 'AdminController.getPromoCodes')
  Route.post('/promo-codes', 'AdminController.savePromoCode')
  Route.post('/promo-codes/calculate', 'AdminController.calculatePromoCodes')
  Route.get('/promo-codes/item/:id/:type', 'AdminController.getPromoCodesByItem')
  Route.post('/promo-codes/item', 'AdminController.savePromoCodesByItem')
  Route.get('/emails', 'AdminController.getEmails')
  Route.get('/emails/:id', 'AdminController.getEmail')
  Route.post('/emails', 'AdminController.saveEmail')
  Route.get('/quotes', 'AdminController.getQuotes')
  Route.post('/quotes/costs', 'AdminController.quoteCosts')
  Route.get('/quotes/:id', 'AdminController.getQuote')
  Route.post('/quotes/:id', 'AdminController.saveQuote')
  Route.get('/quotes/:id/download', 'AdminController.downloadQuote')
  Route.get('/quote-export', 'AdminController.exportQuotes')
  Route.get('/invoices', 'AdminController.getInvoices')
  Route.post('/invoices', 'AdminController.saveInvoice')
  Route.get('/invoices/csv', 'AdminController.invoicesCsv')
  Route.get('/invoices/export', 'AdminController.exportInvoices')
  Route.get('/invoices/b2c', 'AdminController.exportB2C')
  Route.get('/invoices/:id', 'AdminController.getInvoice')
  Route.get('/invoices/:id/payment-reminders', 'AdminController.getPaymentReminders')
  Route.put('/invoices/:id/payment-reminders/:prid', 'AdminController.putPaymentReminder')
  Route.delete('/invoices/:id/payment-reminders/:prid', 'AdminController.deletePaymentReminder')
  Route.put('/invoices/:id/payment-invoices/', 'AdminController.putPaymentInvoice')
  Route.delete('/invoices/:id', 'AdminController.removeInvoice')
  Route.post('/invoices/:id/duplicate', 'AdminController.duplicateInvoice')
  Route.get('/invoices/:id/download', 'AdminController.downloadInvoice')
  Route.get('/daudin', 'AdminController.getDaudin')
  Route.get('/daudin/lines', 'AdminController.getDaudinLines')
  Route.post('/daudin/export', 'AdminController.exportDaudin')
  Route.post('/daudin/import', 'AdminController.importDaudin')
  Route.post('/daudin/returns', 'AdminController.returnsDaudin')
  Route.post('/daudin/stock', 'AdminController.getDaudinStock')
  Route.post('/daudin/missing-project', 'AdminController.getDaudinMissingProject')
  Route.get('/sna/stock', 'SnaController.getStock')
  Route.get('/sna/orders', 'SnaController.getOrders')
  Route.get('/order-manual', 'AdminController.getOrderManual')
  Route.get('/order-manual/:id', 'AdminController.findOrderManual')
  Route.post('/order-manual', 'AdminController.saveOrderManual')
  Route.post('/order-manual/:id/invoice-co', 'AdminController.getOrderManualInvoiceCo')
  Route.get('/order-manual/:id/packing-list', 'AdminController.orderManuelPackingList')
  Route.delete('/order-manual/:id', 'AdminController.deleteOrderManual')
  Route.get('/payments', 'AdminController.getPayments')
  Route.get('/payments/:id', 'AdminController.getPayment')
  Route.delete('/payments/:id', 'AdminController.deletePayment')
  Route.post('/payments/:id/refund', 'AdminController.refundPayment')
  Route.post('/payments', 'AdminController.savePayment')
  Route.get('/goodies', 'AdminController.getGoodies')
  Route.post('/goodies', 'AdminController.saveGoodie')
  Route.delete('/goodies/:id', 'AdminController.deleteGoodie')
  Route.post('/shipping-compare', 'DispatchController.compareShippingOrder')
  Route.get('/shipping-revenues', 'DispatchnController.getShippingRevenues')
  Route.get('/contests', 'ContestController.all')
  Route.post('/contests', 'ContestController.save')
  Route.delete('/contests/:id', 'ContestController.remove')
  Route.post('/contests/:id/extract', 'ContestController.extract')
  Route.get('/shipping-costs', 'AdminController.getShippingCosts')
  Route.get('/stocks', 'AdminController.getStocks')
  Route.get('/stocks/price', 'AdminController.exportStocksPrices')
  Route.get('/elogik/stock', 'ElogikController.getStock')
  Route.get('/elogik/orders', 'ElogikController.getOrders')
  Route.post('/deepl-translate', 'AdminController.deeplTranslate')
  Route.get('/payments-artist', 'AdminController.getPaymentsArtist')
  Route.get('/payments-artist/:id', 'AdminController.getPaymentArtist')
  Route.post('/payments-artist', 'AdminController.savePaymentArtist')
  Route.get('/payments-artist/:id/download', 'AdminController.downloadPaymentArtist')
  Route.delete('/payments-artist/:id', 'AdminController.deletePaymentArtist')
  Route.get('/test-pressing/export', 'AdminController.extractTestPressing')
  Route.get('/direct-pressing/export', 'AdminController.extractDirectPressing')
  Route.get('/logs', 'AdminController.getLogs')
  Route.get('/projects/:id/users', 'ProjectsController.getProjectUsers')
  Route.post('/projects/:project_id/users/:user_id', 'ProjectsController.editProjectUsers')
  Route.delete('/projects/:project_id/users/:user_id', 'ProjectsController.deleteProjectUsers')
  Route.post('/ship-notices', 'AdminController.saveShipNotice')

  Route.group(() => {
    Route.get('/:partner', 'AdminController.getShippingWeightByPartner')
    Route.post('/:id', 'AdminController.updateShippingWeight')
    Route.get('/history/:id', 'AdminController.getShippingWeightHistory')
  }).prefix('shipping-weight')

  Route.group(() => {
    Route.get('/', 'AdminController.getPassCulture')
    Route.put('/save', 'AdminController.savePassCulture')
    Route.delete('/delete/:id', 'AdminController.deletePassCulture')
    Route.get('/export', 'AdminController.exportPassCulture')
  }).prefix('pass-culture')

  // Pass routes
  Route.group(() => {
    Route.get('/quests', 'PassController.getQuests')
    Route.put('/quest', 'PassController.putQuest')
    Route.delete('/quest', 'PassController.deleteQuest')
    Route.get('/history', 'PassController.getHistory')
    Route.put('/history', 'PassController.putHistory')
    Route.delete('/history', 'PassController.deleteHistory')
    Route.get('/raw-levels', 'PassController.getRawLevels')
    Route.get('/levels', 'PassController.getLevels')
    Route.put('/level', 'PassController.putLevel')
    Route.delete('/level', 'PassController.deleteLevel')
    Route.get('/badges', 'PassController.getBadges')
    Route.put('/badge', 'PassController.putBadge')
    Route.delete('/badges/:id', 'PassController.deleteBadge')
    Route.get('/gifts', 'PassController.getGifts')
    Route.put('/gift', 'PassController.putGift')
    Route.delete('/gift/:id', 'PassController.deleteGift')
    Route.get('/update-everyone', 'PassController.updateEveryone')
  }).prefix('pass')
})
  .prefix('admin')
  .middleware(['auth', 'admin'])

Route.group(() => {
  Route.post('/dispatch', 'DispatchController.update')
  Route.post('/dispatchs', 'DispatchController.batch')
  Route.post('/stock', 'DispatchController.updateStock')
  Route.post('/stocks', 'DispatchController.updateStocks')
}).middleware(['api'])
