'use strict'

/*
|--------------------------------------------------------------------------
| Routes
|--------------------------------------------------------------------------
|
| Http routes are entry points to your web application. You can create
| routes for different URL's and bind Controller actions to them.
|
| A complete guide on routing is available here.
| http://adonisjs.com/docs/4.1/routing
|
*/

const Route = use('Route')

Route.get('/', 'AppController.index')

Route.get('/cron', 'AppController.cron')
Route.get('/hourly', 'AppController.hourly')
Route.get('/daily', 'AppController.daily')

Route.get('/test', 'TestController.test')
Route.get('/sitemap.xml', 'AppController.sitemap')
Route.get('/socket.io/', () => '')
Route.post('/socket.io/', () => '')
Route.get('/favicon.ico', () => '')
Route.get('/robots.txt', ({ response }) => {
  response.header('Content-type', 'text/plain')
  return 'User-agent: *\nDisallow: /'
})

/**
Route.get('/loaderio-a0da777c23dadd71d60bd04d8816419d.txt', ({ response }) => {
  response.header('Content-type', 'text/plain')
  return 'loaderio-a0da777c23dadd71d60bd04d8816419d'
})
**/

// Intercom
Route.group(() => {
  // Language conf
  Route.post('/language-conf', 'IntercomController.configureLanguage')

  // Orders bot
  Route.post('/orders-init', 'IntercomController.initOrder')
  Route.post('/orders-submit', 'IntercomController.submitOrder')

  // Account bot
  Route.post('/account-init', 'IntercomController.initAccount')
  Route.post('/account-submit', 'IntercomController.submitAccount')
}).prefix('intercom').middleware('intercom')

Route.group(() => {
  Route.get('/emails/:id', 'AppController.previewEmail')
}).prefix('app').middleware('app')

Route.group(() => {
  Route.get('/styles', 'AppController.getStyles')
  Route.get('/genres', 'AppController.getGenres')
  Route.get('/press', 'AppController.getPress')
  Route.post('/contact', 'AppController.contact')
  Route.get('/boxes', 'BoxController.getLastBoxes')
  Route.get('/boxes/prices', 'BoxController.getBoxesPrices')
  Route.post('/boxes/sponsor', 'BoxController.checkSponsor').middleware(['auth:optional'])
  Route.post('/quote', 'AppController.sendQuote')
  Route.post('/quote/calculate', 'AppController.calculateQuote')

  Route.get('/banners', 'AppController.getBanners')
  Route.get('/home', 'AppController.getHome')

  Route.get('/songs', 'SongsController.all')
  Route.post('/songs/stats', 'SongsController.addPlay')

  Route.post('/payments', 'AppController.payPayment')
  Route.get('/payments/:id', 'AppController.getPayment')
  Route.put('/payments/:id/address', 'AppController.editPaymentAddress')

  Route.post('/comments', 'CommentsController.save')

  Route.get('/blog', 'BlogController.all')
  Route.get('/blog/:id', 'BlogController.find')

  Route.post('projects/check-code', 'ProjectsController.checkCode')
  Route.post('/projects/download', 'ProjectsController.download')
  Route.get('/projects', 'ProjectsController.getProjects')
  Route.get('/projects/all', 'ProjectsController.getAll')
  Route.get('/projects/recommandations', 'ProjectsController.recommandations')
  Route.get('/projects/soundcloud', 'ProjectsController.getSoundcloud')
  Route.get('/projects/statements', 'ProjectsController.getStatements')
  Route.get('/projects/:id', 'ProjectsController.find')
  Route.get('/projects/:id/more', 'ProjectsController.getMore')
  Route.get('/projects/:id/group-shipment', 'ProjectsController.getGroupShipment')
  Route.get('/projects/:id/songs', 'ProjectsController.getSongs')
  Route.get('/projects/:id/edit', 'ProjectsController.findEdit')
  Route.get('/projects/:id/stats', 'ProjectsController.getStats')
  Route.get('/projects/:id/orders', 'ProjectsController.getOrders')
  Route.get('/projects/:id/statement', 'ProjectsController.downloadStatement')
  Route.post('/projects', 'ProjectsController.saveProject')
  Route.post('/projects/:id/artwork', 'ProjectsController.updateArtwork')
  Route.post('/projects/:id/tracks', 'ProjectsController.saveTrack')
  Route.delete('/projects/:project_id/tracks/:id', 'ProjectsController.deleteTrack')

  Route.get('/users', 'UsersController.all')
  Route.get('/users/:id', 'UsersController.find')

  Route.get('/bids/:id', 'BidController.find')
  Route.post('/bids/:id/pay', 'BidController.pay')
  Route.post('/bids/:id/pay-confirm', 'BidController.payConfirm')
  Route.post('/bids/:id/address', 'BidController.editAddress')
  Route.post('/bids/:id/valid', 'BidController.valid')
  Route.post('/bids/:id/cancel', 'BidController.cancel')
}).middleware('auth:optional')

Route.get('/auth/check', 'AuthController.check').middleware(['auth'])
Route.post('/auth/login', 'AuthController.login')
Route.post('/auth/facebook', 'AuthController.facebook')
Route.get('/auth/soundcloud', 'AuthController.soundcloud')
Route.post('/auth/soundcloud', 'AuthController.soundcloud')
Route.post('/auth/signup', 'AuthController.signup')
Route.post('/auth/confirm-email', 'AuthController.confirmEmail')
Route.post('/auth/forgot-password', 'AuthController.forgotPassword')
Route.post('/auth/reset-password', 'AuthController.resetPassword')
Route.post('/auth/unsubscribe-newsletter', 'AuthController.unsubscribeNewsletter')

Route.post('/cart/calculate', 'CartController.calculate').middleware(['auth:optional'])
Route.post('/cart/related', 'CartController.related').middleware(['auth:optional'])
Route.post('/vod/:id/calculate', 'ProjectsController.calculateVod').middleware(['auth:optional'])

Route.get('/contests/:id', 'ContestController.find')
Route.put('/boxes/code', 'CartController.checkBoxCode')

Route.post('/newsletter', 'AppController.subscribeNewsletterWithoutAccount')

Route.get('/catalog', 'AdminController.exportCatalog')

Route.group(() => {
  Route.get('/cart', 'CartController.getCart')
  Route.post('/cart', 'CartController.saveCart')
  Route.delete('/cart', 'CartController.clearCart')
  Route.post('/cart/pay', 'CartController.pay')
  Route.post('/cart/confirm', 'CartController.confirm')
  Route.post('/cart/execute', 'CartController.execute')
  Route.post('/cart/feedback', 'CartController.saveFeedback')
  Route.post('/boxes/code', 'CartController.confirmBoxCode')

  Route.post('/projects/:id/like', 'ProjectsController.like')
  Route.post('/projects/call-me', 'ProjectsController.callMe')

  Route.post('/contests', 'ContestController.join')

  Route.get('/productions', 'ProductionController.all')
  Route.post('/productions', 'ProductionController.create')
  Route.post('/productions/extract', 'ProductionController.extract')
  Route.get('/productions/:id', 'ProductionController.find')
  Route.put('/productions/:id', 'ProductionController.save')
  Route.delete('/productions/:id', 'ProductionController.remove')
  Route.post('/productions/:id/comment', 'ProductionController.saveComment')
  Route.get('/productions/:id/actions', 'ProductionController.getAction')
  Route.post('/productions/:id/actions', 'ProductionController.saveAction')
  Route.get('/productions/:id/download', 'ProductionController.downloadFile')
  Route.get('/productions/:id/zip', 'ProductionController.zipFiles')
  Route.put('/productions/:id/files', 'ProductionController.saveFile')
  Route.delete('/productions/:id/files', 'ProductionController.deleteFile')
  Route.get('/productions/:id/dispatchs', 'ProductionController.getDispatchs')
  Route.post('/productions/:id/dispatchs', 'ProductionController.saveDispatch')
  Route.put('/productions/:id/dispatchs', 'ProductionController.saveDispatchUser')
  Route.get('/productions/:id/dispatchs/:did/file', 'ProductionController.fileDispatch')
  Route.post('/productions/:id/lines', 'ProductionController.saveLines')
  Route.delete('/productions/:id/dispatchs/:did', 'ProductionController.removeDispatch')
}).middleware('auth')

Route.get('/productions/:id/order-form', 'ProductionController.orderForm')

Route.group(() => {
  Route.post('/profile', 'UserController.updateProfile')
  Route.post('/currency', 'UserController.updateCurrency')
  Route.post('/lang', 'UserController.updateLang')
  Route.post('/password', 'UserController.updatePassword')
  Route.post('/delivery', 'UserController.updateDelivery')
  Route.post('/notifications', 'UserController.updateNotifications')
  Route.post('/notifications/view', 'UserController.setNotificationsView')
  Route.post('/picture', 'UserController.updatePicture')
  Route.get('/messages', 'UserController.getMessages')
  Route.post('/messages', 'UserController.sendMessage')
  Route.get('/messages/:from', 'UserController.getMessagesByUser')
  Route.get('/projects', 'UserController.getProjects')
  Route.get('/projects/:id/orders', 'UserController.getProjectOrders')
  Route.get('/projects/:id/extract-orders', 'UserController.extractProjectOrders')
  Route.get('/orders', 'UserController.getOrders')
  Route.get('/orders/:id/tracking', 'UserController.getTrackingDelivery')
  Route.get('/orders/:id/shop', 'UserController.getOrderShop')
  Route.put('/orders/:id/customer', 'UserController.updateOrderCustomer')
  Route.delete('/orders/:id', 'UserController.cancelOrder')
  Route.get('/boxes', 'UserController.getBoxes')
  Route.put('/boxes', 'UserController.changeBox')
  Route.post('/boxes/vinyl', 'UserController.selectBoxVinyl')
  Route.post('/boxes/invoice', 'UserController.boxInvoice')
  Route.post('/boxes/payment', 'UserController.changeBoxPayment')
  Route.post('/boxes/address', 'UserController.changeBoxAddress')
  Route.get('/boxes/:id/card', 'UserController.getBoxCard')
  Route.delete('/boxes/:id', 'UserController.cancelBox')
  Route.get('/digs', 'UserController.getDigs')
  Route.get('/cards', 'UserController.getCards')
  Route.post('/cards', 'UserController.saveCards')
  Route.post('/event', 'UserController.event')
  Route.get('/sponsor', 'UserController.getSponsor')
}).prefix('user').middleware(['auth'])

Route.group(() => {
  Route.get('/stats', 'AdminController.getStats')
  Route.get('/stats2', 'AdminController.getStats2')
  Route.get('/business', 'AdminController.getBusiness')
  Route.get('/resp-prod', 'AdminController.getRespProd')
  Route.get('/stripe-balance', 'AdminController.getStripeBalance')
  Route.post('/customers', 'AdminController.saveCustomer')
  Route.get('/projects', 'AdminController.getProjects')
  Route.get('/projects/export', 'AdminController.exportProjects')
  Route.get('/projects/balance', 'AdminController.getBalances')
  Route.get('/projects/:id', 'AdminController.getProject')
  Route.post('/projects/:id', 'AdminController.saveProject')
  Route.get('/projects/:id/balance', 'AdminController.getBalance')
  Route.post('/projects/:id/send-notif', 'AdminController.sendProjectNotif')
  Route.get('/projects/:id/code-download', 'App/Project.codeDownload')
  Route.post('/projects/:id/tracks', 'AdminController.uploadTracks')
  Route.post('/projects/:id/transfer', 'AdminController.transferStripe')
  Route.post('/projects/:id/reverse', 'AdminController.reverseStripe')
  Route.post('/projects/:id/payout', 'AdminController.payoutStripe')
  Route.get('/projects/:id/statements', 'AdminController.getStatements')
  Route.post('/projects/:id/statements', 'AdminController.saveStatement')
  Route.post('/projects/:id/images', 'AdminController.saveProjectImage')
  Route.put('/projects/:id/images/:iid', 'AdminController.updateProjectImage')
  Route.delete('/projects/:id/images/:iid', 'AdminController.deleteProjectImage')
  Route.get('/projects/:id/statements/download', 'AdminController.downloadStatement')
  Route.delete('/projects/:id/statements/:sid', 'AdminController.deleteStatement')
  Route.delete('/projects/:id', 'AdminController.deleteProject')
  Route.get('/projects/:id/stats', 'AdminController.getProjectStats')
  Route.get('/projects/:id/orders/extract', 'AdminController.extractOrders')
  Route.get('/projects/:id/check-sync', 'AdminController.checkSync')
  Route.post('/projects/:id/orders/sync-project', 'AdminController.syncProject')
  Route.get('/projects/:id/calcul-stock', 'AdminController.calculStock')
  Route.get('/projects/:id/songs', 'AdminController.downloadProject')
  Route.get('/projects/:id/promo-kit', 'AdminController.downloadPromoKit')
  Route.post('/projects/:id/duplicate', 'AdminController.duplicateProject')
  Route.get('/projects/:id/export-mails/:lang', 'AdminController.exportEmails')
  Route.post('/projects/:id/generate-download', 'AdminController.generateDownloads')
  Route.get('/projects/:id/download-codes', 'AdminController.downloadCodes')
  Route.post('/projects/:id/balance', 'AdminController.getBalanceProject')
  Route.post('/projects/:id/costs', 'AdminController.storeCosts')
  Route.delete('/projects/:id/picture', 'AdminController.removePicture')
  Route.delete('/projects/:id/costs', 'AdminController.deleteCost')
  Route.get('/projects/:id/productions', 'AdminController.getProjectProductions')
  Route.get('/projects/:id/costs/:cid/download', 'AdminController.downloadInvoiceCost')
  Route.get('/projects/facebook', 'AdminController.exportFacebookProjects')
  Route.post('/statements', 'AdminController.uploadStatement')
  Route.post('/items', 'AdminController.saveProjectItem')
  Route.delete('/items/:id', 'AdminController.removeProjectItem')
  Route.post('/projects/:id/refund', 'AdminController.refundProject')
  Route.get('/wishlists', 'AdminController.getWishlists')
  Route.post('/stripe/:id', 'AdminController.updateAccount')
  Route.delete('/stripe/:id', 'AdminController.deleteAccount')
  Route.get('/orders/errors', 'AdminController.countOrdersError')
  Route.get('/orders', 'AdminController.getOrders')
  Route.get('/orders/:id', 'AdminController.getOrder')
  Route.get('/orders-shop/:id', 'AdminController.getOrderShop')
  Route.get('/ordershops/:id/invoice', 'AdminController.getOrderShopInvoice')
  Route.post('/orders', 'AdminController.saveOrder')
  Route.get('/order-export', 'AdminController.extractOrders')
  Route.get('/sales-export', 'AdminController.exportSales')
  Route.post('/orders/:id', 'AdminController.saveOrderShop')
  Route.post('/orders/:id/items', 'AdminController.saveOrderItem')
  Route.get('/orders/:id/download', 'AdminController.downloadOrder')
  Route.post('/orders/:id/refund', 'AdminController.refundOrder')
  Route.post('/orders/:id/credit-note', 'AdminController.orderCreditNote')
  Route.post('/orders/:id/shipping-payment', 'AdminController.shippingPayment')
  Route.post('/orders/:id/pickup-change', 'AdminController.pickupMustChange')
  Route.delete('/orders/:id/refund', 'AdminController.refundOrderShop')
  Route.delete('/orders/:id', 'AdminController.cancelOrderShop')
  Route.get('/feedbacks', 'AdminController.getFeedbacks')
  Route.get('/boxes', 'BoxController.getBoxes')
  Route.get('/boxes/export', 'BoxController.exportBoxes')
  Route.get('/boxes/dispatchs', 'BoxController.statsDispatchs')
  Route.get('/boxes/months', 'BoxController.getBoxMonths')
  Route.post('/boxes/months', 'BoxController.saveBoxMonth')
  Route.delete('/boxes/months', 'BoxController.removeBoxMonth')
  Route.get('/boxes/stats', 'BoxController.getBoxesStats')
  Route.get('/boxes/codes', 'BoxController.getBoxCodes')
  Route.post('/boxes/codes', 'BoxController.saveBoxCode')
  Route.get('/boxes/:id', 'BoxController.getBox')
  Route.get('/boxes/:id/card', 'BoxController.getBoxCard')
  Route.post('/boxes/dispatch', 'BoxController.saveDispatch')
  Route.get('/boxes/dispatch/:id/invoice', 'BoxController.invoiceDispatch')
  Route.post('/boxes/:id', 'BoxController.saveBox')
  Route.post('/boxes/check', 'BoxController.checkPayments')
  Route.delete('/boxes/:id/payments/:pid', 'BoxController.refundBoxPayment')
  Route.delete('/boxes/dispatch/:id', 'BoxController.removeDispatch')
  Route.get('/barcodes/:code', 'ProjectsController.getBarcode')
  Route.get('/users', 'AdminController.getUsers')
  Route.get('/users/extract', 'AdminController.extractUsers')
  Route.get('/users/audiences', 'AdminController.getAudiences')
  Route.post('/users/unsub', 'AdminController.newsletterUnsub')
  Route.get('/users/:id', 'AdminController.getUser')
  Route.get('/users/:id/emails', 'AdminController.getUserEmails')
  Route.delete('/users/:id', 'AdminController.deleteUser')
  Route.post('/users/:id', 'AdminController.saveUser')
  Route.post('/users/:id/digs', 'AdminController.addDig')
  Route.get('/users/:id/statements', 'AdminController.getUserStatements')
  Route.get('/newsletters', 'AdminController.getNewsletters')
  Route.post('/newsletters/template', 'AdminController.getNewsletterTemplate')
  Route.get('/newsletters/:id', 'AdminController.getNewsletter')
  Route.post('/newsletters/:id', 'AdminController.saveNewsletter')
  Route.post('/newsletters/:id/clear-list', 'AdminController.clearNewsletterList')
  Route.post('/newsletters/:id/send', 'AdminController.sendNewsletter')
  Route.post('/newsletters/:id/send-test', 'AdminController.sendNewsletterTest')
  Route.delete('/newsletters/:id', 'AdminController.deleteNewsletter')
  Route.get('/articles', 'AdminController.getArticles')
  Route.get('/articles/:id', 'AdminController.getArticle')
  Route.post('/articles/:id', 'AdminController.saveArticle')
  Route.delete('/articles/:id', 'AdminController.deleteArticle')
  Route.get('/ban', 'AdminController.getBanners')
  Route.post('/ban', 'AdminController.saveBanner')
  Route.get('/ban/:id', 'AdminController.getBanner')
  Route.delete('/ban/:id', 'AdminController.deleteBanner')
  Route.get('/categories', 'AdminController.getCategories')
  Route.get('/categories/:id', 'AdminController.getCategory')
  Route.post('/categories/:id', 'AdminController.saveCategory')
  Route.post('/categories/:id/populate', 'AdminController.populateProjectsCategory')
  Route.delete('/categories/:id/deleteAll', 'AdminController.deleteAllProjectsCategory')
  Route.delete('/categories/:id', 'AdminController.deleteCategory')
  Route.get('/surveys', 'AdminController.getSurveys')
  Route.get('/surveys/:id', 'AdminController.getSurvey')
  Route.post('/surveys/:id', 'AdminController.saveSurvey')
  Route.get('/listing', 'AdminController.getListings')
  Route.get('/listing/:id', 'AdminController.getListing')
  Route.post('/listing/:id', 'AdminController.saveListing')
  Route.delete('/listing/:id', 'AdminController.deleteListing')
  Route.get('/propects', 'AdminController.getPropects')
  Route.post('/propects', 'AdminController.newProspect')
  Route.put('/propects', 'AdminController.updateProspect')
  Route.delete('/propects/:id', 'AdminController.deleteProspect')
  Route.get('/labels', 'AdminController.getLabels')
  Route.get('/labels/:id', 'AdminController.getLabel')
  Route.post('/labels', 'AdminController.saveLabel')
  Route.delete('/labels/:id', 'AdminController.deleteLabel')
  Route.post('/labels/:id/copy', 'AdminController.copyLabel')
  Route.get('/parse-label', 'AdminController.parseLabels')
  Route.get('/marketplaces', 'AdminController.getMarketplaces')
  Route.get('/marketplaces/:id', 'AdminController.getMarketplace')
  Route.post('/marketplaces/:id', 'AdminController.saveMarketplace')
  Route.post('/styles', 'AdminController.saveStyles')
  Route.get('/sponsors', 'AdminController.getSponsors')
  Route.post('/sponsors', 'AdminController.saveSponsor')
  Route.get('/promo-codes', 'AdminController.getPromoCodes')
  Route.post('/promo-codes', 'AdminController.savePromoCode')
  Route.post('/promo-codes/calculate', 'AdminController.calculatePromoCodes')
  Route.get('/emails', 'AdminController.getEmails')
  Route.get('/emails/:id', 'AdminController.getEmail')
  Route.post('/emails', 'AdminController.saveEmail')
  Route.get('/quotes', 'AdminController.getQuotes')
  Route.post('/quotes/costs', 'AdminController.quoteCosts')
  Route.get('/quotes/:id', 'AdminController.getQuote')
  Route.post('/quotes/:id', 'AdminController.saveQuote')
  Route.get('/quotes/:id/download', 'AdminController.downloadQuote')
  Route.get('/invoices', 'AdminController.getInvoices')
  Route.post('/invoices', 'AdminController.saveInvoice')
  Route.get('/invoices/sfc', 'AdminController.invoicesSfc')
  Route.get('/invoices/csv', 'AdminController.invoicesCsv')
  Route.get('/invoices/export', 'AdminController.exportInvoices')
  Route.get('/invoices/:id', 'AdminController.getInvoice')
  Route.delete('/invoices/:id', 'AdminController.removeInvoice')
  Route.post('/invoices/:id/duplicate', 'AdminController.duplicateInvoice')
  Route.get('/invoices/:id/download', 'AdminController.downloadInvoice')
  Route.get('/daudin', 'AdminController.getDaudin')
  Route.get('/daudin/lines', 'AdminController.getDaudinLines')
  Route.post('/daudin/export', 'AdminController.exportDaudin')
  Route.post('/daudin/import', 'AdminController.importDaudin')
  Route.post('/daudin/returns', 'AdminController.returnsDaudin')
  Route.post('/daudin/stock', 'AdminController.getDaudinStock')
  Route.post('/daudin/missing-project', 'AdminController.getDaudinMissingProject')
  Route.get('/sna/stock', 'SnaController.getStock')
  Route.get('/order-manual', 'AdminController.getOrderManual')
  Route.post('/order-manual', 'AdminController.saveOrderManual')
  Route.delete('/order-manual/:id', 'AdminController.deleteOrderManual')
  Route.get('/payments', 'AdminController.getPayments')
  Route.get('/payments/:id', 'AdminController.getPayment')
  Route.delete('/payments/:id', 'AdminController.deletePayment')
  Route.post('/payments/:id/refund', 'AdminController.refundPayment')
  Route.post('/payments', 'AdminController.savePayment')
  Route.get('/goodies', 'AdminController.getGoodies')
  Route.post('/goodies', 'AdminController.saveGoodie')
  Route.delete('/goodies/:id', 'AdminController.deleteGoodie')
  Route.post('/shipping-compare', 'AdminController.compareShippingOrder')
  Route.get('/shipping-revenues', 'AdminController.getShippingRevenues')
  Route.get('/contests', 'ContestController.all')
  Route.post('/contests', 'ContestController.save')
  Route.delete('/contests/:id', 'ContestController.remove')
  Route.post('/contests/:id/extract', 'ContestController.extract')
}).prefix('admin').middleware(['auth', 'admin'])

Route.group(() => {
  Route.post('/dispatch', 'DispatchController.update')
  Route.post('/dispatchs', 'DispatchController.batch')
  Route.post('/stock', 'DispatchController.updateStock')
  Route.post('/stocks', 'DispatchController.updateStocks')
}).middleware(['api'])
